### ISSUE TITLE
create user through terminal successful but cant login

### ISSUE THREAD

**Issue by motherfogger** [Putaitu/putaitu-cms#170]
node hashbrown.js create-user u=ace p=acepw admin=true

i cant login after creating an admin user but when i create the same username, it knows that it is duplicated.

i cant see the db changes in mongo(terminal)

when im logging in, 

```2017.03.23 01:52:37 | UserHelper | Attempting login for user "ace"...
2017.03.23 01:52:37 | UserController | ERROR: Error: Invalid password
    at findUser.then (/home/looper/spheria/hashbrown-cms/src/server/helpers/UserHelper.js:203:39)
    at tryCatcher (/home/looper/spheria/hashbrown-cms/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/looper/spheria/hashbrown-cms/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/looper/spheria/hashbrown-cms/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/looper/spheria/hashbrown-cms/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/looper/spheria/hashbrown-cms/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/looper/spheria/hashbrown-cms/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/looper/spheria/hashbrown-cms/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/looper/spheria/hashbrown-cms/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
```

**Comment by mrzapp** [comment]
The user collection in MongoDB is called "users", you should be able to see your changes there. You can always just do a db.users.drop() if you want to start fresh.

The latest stable version (0.7.0) comes with a first-time setup mode though, so you might want to try that out. Just Start a fresh instance, and it should appear.

**Comment by mrzapp** [comment]
Did you manage to get past this issue? As far as your output goes, an invalid password was provided.

**Comment by motherfogger** [comment]
im pulling your latest changes. i'll just try again

**Comment by motherfogger** [comment]
this one works: node hashbrown.js create-user u="ace3" p="letmepass" admin=true

the "" is the issue. haha

**Comment by mrzapp** [comment]
Ah, ok. Maybe we should make those quotes optional. In any case, admins can be created without the terminal now anyway.
