### ISSUE TITLE
Error when creating a new form

### ISSUE THREAD

**Issue by jfrux** [Putaitu/putaitu-cms#222]
Sorry for this but I'm new around here...

I'm getting an error on creating a new "Form"... still trying to learn what the different screens do.

```
TypeError: HashBrown.Models.Form is not a constructor
    at postForm (/Users/joshua/Projects/openpilot-db/src/Server/Controllers/FormsController.js:223:91)
    at Layer.handle [as handle_request] (/Users/joshua/Projects/openpilot-db/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/joshua/Projects/openpilot-db/node_modules/express/lib/router/route.js:137:13)
    at ApiController.checkCORS.then.then (/Users/joshua/Projects/openpilot-db/src/Server/Controllers/ApiController.js:105:17)
    at tryCatcher (/Users/joshua/Projects/openpilot-db/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/joshua/Projects/openpilot-db/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/joshua/Projects/openpilot-db/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/joshua/Projects/openpilot-db/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/joshua/Projects/openpilot-db/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/joshua/Projects/openpilot-db/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/joshua/Projects/openpilot-db/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/joshua/Projects/openpilot-db/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
```

**Comment by mrzapp** [comment]
That was a bug, the "Form" class was not in the "Server.Models" namespace. It's fixed now, and a new patch has been released. Thank you for reporting this error, it helps a lot :)
